### ISSUE TITLE
getIngredients Database Service

### ISSUE THREAD

**Issue by StewartSmyth** [StewartSmyth/SEPP-Project-2024#12]
Database service which takes in the housename of the house.
Returns the ingredient and ingredient_name using something similar to follinging request.

Selects ingredient.ingredient_id, ingredient.ingredient_name
From Ingredient
Join house_ingredient On house_ingredient.ingredient_id = ingredient.ingredient_id
Join house On house.house_id = house_ingredient.house_id
where house.name = username

**Comment by Deevun155** [comment]
resolved by #16
