### ISSUE TITLE
getRecipes database service

### ISSUE THREAD

**Issue by StewartSmyth** [StewartSmyth/SEPP-Project-2024#13]
Database service which takes in the housename of the house
Returns data to populate the frontend table except the ingredients: recipe_id, recipe_name, recipe_time, recipe_link using similar method to the following

Firstly run the getIngredients service to get all the ingredient_ids which the house has

For each ingredient from this query run the following and add to the return list of recipes only recipes which have not already been added, then add the ingredient_name to the recipe's ingredient list the request should look like the following:

Select recipe.recipe_id, recipe_name, recipe_cooking_time, reipe_link
From recipe
Join recipe_ingredient On recipe.recipe_id = recipe_ingredient.recipe_id
Where recipe_ingredient.ingredient_id = ingredient_id

**Comment by Deevun155** [comment]
resolved by #16
